{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app1.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app1.labels" . | nindent 4 }}
type: Opaque
data:
  {{- toYaml .Values.secret.data | nindent 2 }}
{{- end }}
